[WIP] Fix/rich previews
voorhoede/heads-up pull request #280
Opened 2023-05-01 13:27 UTC by vvandijck

(Short description if needed)

## What change(s) were made
- Fixed dependency errors.
- Load in Vue from a local file instead from a remote source (caused CSP issue)
- Post window height from within `<iframe>` to it's parent window using `postMessage()` (previous solution caused CSP issue)

## TODO
- [ ] Edit `content_security_policy` to allow for `<script>` tags within the rich preview's `<iframe>`'s.

Using the Twitter rich preview as an example. Fix the following:
- [ ] Get Facebook rich preview working again.
- [ ] Get LinkedIn rich preview working again.
- [ ] Get OpenSearch rich preview working again.
- [ ] Get Slack rich preview working again.
- [ ] Get Whatsapp rich preview working again.

## Checks
- [ ] Checked browser extension (light & dark theme).
- [ ] Checked web app.
- [ ] ...

2023-05-05 08:55 UTC, Siilwyn commented
> Some of our DatoCMS plugins use these previews. That was broken, and should now be restored once this has been merged.
Which plugins specifically? And in what way did they break? Since we concluded earlier it's best to remove the google preview I'm wary of adding it back.

2023-05-12 13:15 UTC, Jamerrone requested changes
Looking good, I pretty much only have 1 feedback. A lot of the Google components have a `h1` tag in them, that was fine as an iFrame but not so much as a component. We don't want to render multiple `h1`'s in a single page.

2023-05-12 13:15 UTC, Jamerrone commented on projects/@shared/components/rich-previews/google-article-desktop-preview.vue
> +    <h1 class="iframe-heading" :class="{ 'iframe-heading--dark-mode': isDarkMode }">NewsArticle</h1>
We probably don't want to use a `h1` tag any more, it was fine inside an iFrame but not in a component.

2023-05-12 13:15 UTC, Jamerrone commented on projects/@shared/components/rich-previews/google-article-mobile-preview.vue
> +    <h1 class="iframe-heading" :class="{ 'iframe-heading--dark-mode': isDarkMode }">NewsArticle</h1>
We probably don't want to use a `h1` tag any more, it was fine inside an iFrame but not in a component.

2023-05-12 13:15 UTC, Jamerrone commented on projects/@shared/components/rich-previews/google-breadcrumb-preview.vue
> +    <h1 class="iframe-heading" :class="{ 'iframe-heading--dark-mode': isDarkMode }">Breadcrumb</h1>
We probably don't want to use a `h1` tag any more, it was fine inside an iFrame but not in a component.

2023-05-12 13:15 UTC, Jamerrone commented on projects/@shared/components/rich-previews/google-course-preview.vue
> +    <h1 class="iframe-heading" :class="{ 'iframe-heading--dark-mode': isDarkMode }">Course</h1>
We probably don't want to use a `h1` tag any more, it was fine inside an iFrame but not in a component.

2023-05-12 13:15 UTC, Jamerrone commented on projects/@shared/components/rich-previews/google-product-desktop-preview.vue
> +    <h1 class="iframe-heading" :class="{ 'iframe-heading--dark-mode': isDarkMode }">Product</h1>
We probably don't want to use a `h1` tag any more, it was fine inside an iFrame but not in a component.

2023-05-12 13:15 UTC, Jamerrone commented on projects/@shared/components/rich-previews/google-product-mobile-preview.vue
> +    <h1 class="iframe-heading" :class="{ 'iframe-heading--dark-mode': isDarkMode }">Product</h1>
We probably don't want to use a `h1` tag any more, it was fine inside an iFrame but not in a component.

2023-05-12 13:15 UTC, Jamerrone commented on projects/@shared/components/rich-previews/google-review-preview.vue
> +    <h1 class="iframe-heading" :class="{ 'iframe-heading--dark-mode': isDarkMode }">Critic review</h1>
We probably don't want to use a `h1` tag any more, it was fine inside an iFrame but not in a component.

2023-05-12 14:36 UTC, Jamerrone approved these changes

2023-05-15 06:56 UTC, merged