feat(properties-item): update validationSchema on changes in head
voorhoede/heads-up pull request #65
Opened 2020-02-26 15:39 UTC by RobinStut

2020-02-26 15:43 UTC, RobinStut commented on src/heads-up/components/properties-item.vue
> +      this.errors = validateSchema(schemaTemplate)
I put this schemaTemplate in a const to reuse later on. I am planning to create multiple validation functions like rule 166

2020-02-26 16:07 UTC, Jamerrone requested changes
You are missing 2 spaces.

2020-02-26 16:07 UTC, Jamerrone commented on src/heads-up/components/properties-item.vue
> +    'head'(){
`'head'() {`

2020-02-26 16:07 UTC, Jamerrone commented on src/heads-up/components/properties-item.vue
> +    validateSchema(){
`validateSchema() {`

2020-02-27 08:51 UTC, Jamerrone approved these changes

2020-03-03 08:28 UTC, merged